// Watches AudioLibrary assets for changes and regenerates a C# constants file
// containing static AudioHandle fields - one per SFX entry, one per Music entry.
//
// Generated output example (namespace CorePro.AudioSystem.Generated):
//
//   public static class SFX
//   {
//       /// <summary>Weapons/Pistol/Shoot</summary>
//       public static readonly AudioHandle Weapons_Pistol_Shoot = ...;
//   }
//
//   public static class Music
//   {
//       /// <summary>Combat/MainTheme</summary>
//       public static readonly AudioHandle Combat_MainTheme = ...;
//   }
//
// The file is written to the folder specified by AudioLibrary.generatedCodeFolder.
// Regeneration is triggered manually via the Regenerate Constants button in the Audio Library Editor.

#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CorePro.AudioSystem.Editor
{
    /// <summary>
    /// Generates a C# constants file with static AudioHandle fields.
    /// Triggered manually via the Audio Library Editor window (Regenerate Constants button).
    /// Auto-regeneration on save is intentionally disabled - writing a new .cs file
    /// triggers a domain reload which disrupts editor workflow.
    /// </summary>
    internal sealed class AudioConstantsGenerator
    {
        // Public entry point - called from EditorWindow button only 

        internal static void RegenerateAll()
        {
            EditorApplication.delayCall -= RegenerateAll;

            string[] guids = AssetDatabase.FindAssets("t:AudioLibrary");
            if (guids.Length == 0)
                return;

            // Use the first library's settings for output path and namespace;
            // all entries from all libraries are merged into a single file.
            AudioLibrary primary = null;
            var allSFX   = new List<(string path, AudioHandle handle)>();
            var allMusic = new List<(string path, AudioHandle handle)>();

            foreach (string guid in guids)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                var lib = AssetDatabase.LoadAssetAtPath<AudioLibrary>(assetPath);
                if (lib == null) continue;

                primary ??= lib;

                for (int i = 0; i < lib.SFX.Count; i++)
                {
                    var entry = lib.SFX[i];
                    if (entry == null || string.IsNullOrWhiteSpace(entry.name)) continue;
                    allSFX.Add((entry.name, lib.MakeSFXHandle(i)));
                }

                for (int i = 0; i < lib.Music.Count; i++)
                {
                    var entry = lib.Music[i];
                    if (entry == null || string.IsNullOrWhiteSpace(entry.name)) continue;
                    allMusic.Add((entry.name, lib.MakeMusicHandle(i)));
                }
            }

            if (primary == null) 
                return;

            allSFX.Sort((a, b)   => string.Compare(a.path, b.path, StringComparison.Ordinal));
            allMusic.Sort((a, b) => string.Compare(a.path, b.path, StringComparison.Ordinal));

            string code = GenerateCode(primary, allSFX, allMusic);
            WriteFile(primary, code);
        }

        // Code generation 

        private static string GenerateCode(
            AudioLibrary                        primary,
            List<(string path, AudioHandle h)>  sfx,
            List<(string path, AudioHandle h)>  music)
        {
            string ns  = string.IsNullOrWhiteSpace(primary.generatedNamespace)
                ? "CorePro.Audio.Generated"
                : primary.generatedNamespace;

            var sb = new StringBuilder(4096);

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated automatically by CorePro AudioConstantsGenerator.");
            sb.AppendLine("// DO NOT EDIT MANUALLY - changes will be overwritten on next library save.");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using CorePro.Audio;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // SFX class 
            sb.AppendLine("    /// <summary>Auto-generated SFX handle constants.</summary>");
            sb.AppendLine("    public static class SFX");
            sb.AppendLine("    {");

            if (sfx.Count == 0)
            {
                sb.AppendLine("        // No SFX entries found in any AudioLibrary.");
            }
            else
            {
                foreach ((string path, AudioHandle handle) in sfx)
                {
                    string fieldName = PathToFieldName(path);
                    long   packed    = GetPacked(handle);
                    sb.AppendLine($"        /// <summary>{EscapeXml(path)}</summary>");
                    sb.AppendLine($"        public static readonly AudioHandle {fieldName} =");
                    sb.AppendLine($"            AudioHandleFactory.FromPacked({packed}L);");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // Music class 
            sb.AppendLine("    /// <summary>Auto-generated Music handle constants.</summary>");
            sb.AppendLine("    public static class Music");
            sb.AppendLine("    {");

            if (music.Count == 0)
            {
                sb.AppendLine("        // No Music entries found in any AudioLibrary.");
            }
            else
            {
                foreach ((string path, AudioHandle handle) in music)
                {
                    string fieldName = PathToFieldName(path);
                    long   packed    = GetPacked(handle);
                    sb.AppendLine($"        /// <summary>{EscapeXml(path)}</summary>");
                    sb.AppendLine($"        public static readonly AudioHandle {fieldName} =");
                    sb.AppendLine($"            AudioHandleFactory.FromPacked({packed}L);");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void WriteFile(AudioLibrary primary, string code)
        {
            string folder  = primary.generatedCodeFolder?.Trim('/').Trim('\\') ?? "CorePro/Generated";
            string absDir  = Path.Combine(Application.dataPath, folder);
            string absFile = Path.Combine(absDir, "AudioConstants.cs");

            try
            {
                Directory.CreateDirectory(absDir);
                File.WriteAllText(absFile, code, Encoding.UTF8);

                // Refresh so Unity picks up the new file
                string assetPath = $"Assets/{folder}/AudioConstants.cs";
                AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);

                Debug.Log($"[CorePro Audio] Constants regenerated -> {assetPath}");
            }
            catch (Exception ex)
            {
                Debug.LogError($"[CorePro Audio] Failed to write constants file: {ex.Message}");
            }
        }

        // Helpers 

        /// <summary>
        /// Converts a slash-separated path to a valid C# identifier.
        /// "Weapons/Pistol/Shoot" -> "Weapons_Pistol_Shoot"
        /// </summary>
        private static string PathToFieldName(string path)
        {
            var sb = new StringBuilder(path.Length + 4);
            bool nextUpper = false;

            foreach (char c in path)
            {
                if (c == '/' || c == '\\' || c == ' ')
                {
                    if (sb.Length > 0) sb.Append('_');
                    nextUpper = true;
                    continue;
                }

                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                else
                    sb.Append('_');

                nextUpper = false;
            }

            string name = sb.ToString().Trim('_');

            // Ensure it doesn't start with a digit
            if (name.Length > 0 && char.IsDigit(name[0]))
                name = "_" + name;

            return string.IsNullOrEmpty(name) ? "_Unknown" : name;
        }

        private static string EscapeXml(string s) =>
            s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        // Reinterpret AudioHandle bits as long via MemoryMarshal - no unsafe needed.
        // AudioHandle is a single-field struct { long _packed }, layout is identical.
        private static long GetPacked(AudioHandle handle) =>
            System.Runtime.InteropServices.MemoryMarshal.Read<long>(
                System.Runtime.InteropServices.MemoryMarshal.AsBytes(
                    System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref handle, 1)));
    }

    // =========================================================================
    // AudioHandleFactory - used exclusively by generated code
    // =========================================================================
    // This small public class lives here (Editor folder is fine for the generator
    // but AudioHandleFactory must be in Runtime so generated code can reference it).
    // We define it here for completeness; in practice move it to Runtime folder.
    // See AudioHandleFactory.cs (created as a separate Runtime file).
}
#endif